{{- $cowboys := .Files.Get "cowboys.json" | fromJson -}}
{{- range $cowboys }}
apiVersion: v1
kind: Pod
metadata:
  name: cowboy-{{ .name | lower }}
  namespace: k8s-cowboy-shootout
  labels:
    app.kubernetes.io/part-of: k8s-cowboy-shootout
    app.kubernetes.io/name: cowboy
spec:
  restartPolicy: Never
  serviceAccountName: cowboy
  containers:
  - name: cowboy
    image: ghcr.io/mariouhrik/k8s-cowboy-shootout/cowboy:latest
    env:
    - name: COWBOY_NAME
      value: "{{ .name }}"
    - name: COWBOY_HEALTH
      value: "{{ .health }}"
    - name: COWBOY_DAMAGE
      value: "{{ .damage }}"
    - name: K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    ports:
    - containerPort: 8080
    readinessProbe:
      grpc:
        port: 8080
      periodSeconds: 1
      failureThreshold: 1
---
{{- end }} 
apiVersion: v1
kind: Service
metadata:
  name: cowboys
  namespace: k8s-cowboy-shootout
  labels:
    app.kubernetes.io/part-of: k8s-cowboy-shootout
    app.kubernetes.io/name: cowboy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/part-of: k8s-cowboy-shootout
    app.kubernetes.io/name: cowboy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cowboy
  namespace: k8s-cowboy-shootout
  labels:
    app.kubernetes.io/part-of: k8s-cowboy-shootout
    app.kubernetes.io/name: cowboy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cowboy
  namespace: k8s-cowboy-shootout
  labels:
    app.kubernetes.io/part-of: k8s-cowboy-shootout
    app.kubernetes.io/name: cowboy
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cowboy
  namespace: k8s-cowboy-shootout
  labels:
    app.kubernetes.io/part-of: k8s-cowboy-shootout
    app.kubernetes.io/name: cowboy
subjects:
- kind: ServiceAccount
  name: cowboy
roleRef:
  kind: Role
  name: cowboy
  apiGroup: rbac.authorization.k8s.io