apiVersion: apps/v1
kind: Deployment
metadata:
  name: referee
  labels:
    app: k8s-cowboy-shootout
    microservice: referee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-cowboy-shootout
      microservice: referee
  template:
    metadata:
      labels:
        app: k8s-cowboy-shootout
        microservice: referee
    spec:
      containers:
        - name: referee
          image: ghcr.io/mariouhrik/k8s-cowboy-shootout/referee:latest
          env:
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          readinessProbe:
            tcpSocket:
              port: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
